// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/voronovsg/rocket-factory/inventory/internal/model"
)

// NewMockPartRepository creates a new instance of MockPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartRepository {
	mock := &MockPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPartRepository is an autogenerated mock type for the PartRepository type
type MockPartRepository struct {
	mock.Mock
}

type MockPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartRepository) EXPECT() *MockPartRepository_Expecter {
	return &MockPartRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) Get(ctx context.Context, uuid string) (model.Part, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockPartRepository_Expecter) Get(ctx interface{}, uuid interface{}) *MockPartRepository_Get_Call {
	return &MockPartRepository_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *MockPartRepository_Get_Call) Run(run func(ctx context.Context, uuid string)) *MockPartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartRepository_Get_Call) Return(part model.Part, err error) *MockPartRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockPartRepository_Get_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Part, error)) *MockPartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InitGenParts provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) InitGenParts(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitGenParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPartRepository_InitGenParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitGenParts'
type MockPartRepository_InitGenParts_Call struct {
	*mock.Call
}

// InitGenParts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPartRepository_Expecter) InitGenParts(ctx interface{}) *MockPartRepository_InitGenParts_Call {
	return &MockPartRepository_InitGenParts_Call{Call: _e.mock.On("InitGenParts", ctx)}
}

func (_c *MockPartRepository_InitGenParts_Call) Run(run func(ctx context.Context)) *MockPartRepository_InitGenParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPartRepository_InitGenParts_Call) Return(err error) *MockPartRepository_InitGenParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPartRepository_InitGenParts_Call) RunAndReturn(run func(ctx context.Context) error) *MockPartRepository_InitGenParts_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) List(ctx context.Context, filter model.PartsFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPartRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartsFilter
func (_e *MockPartRepository_Expecter) List(ctx interface{}, filter interface{}) *MockPartRepository_List_Call {
	return &MockPartRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockPartRepository_List_Call) Run(run func(ctx context.Context, filter model.PartsFilter)) *MockPartRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(model.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartRepository_List_Call) Return(parts []model.Part, err error) *MockPartRepository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockPartRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter model.PartsFilter) ([]model.Part, error)) *MockPartRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
