// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/voronovsg/rocket-factory/notification/internal/model"
)

// NewMockTelegramService creates a new instance of MockTelegramService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelegramService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelegramService {
	mock := &MockTelegramService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelegramService is an autogenerated mock type for the TelegramService type
type MockTelegramService struct {
	mock.Mock
}

type MockTelegramService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelegramService) EXPECT() *MockTelegramService_Expecter {
	return &MockTelegramService_Expecter{mock: &_m.Mock}
}

// SendOrderAssembledNotification provides a mock function for the type MockTelegramService
func (_mock *MockTelegramService) SendOrderAssembledNotification(ctx context.Context, event model.OrderAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderAssembledNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTelegramService_SendOrderAssembledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderAssembledNotification'
type MockTelegramService_SendOrderAssembledNotification_Call struct {
	*mock.Call
}

// SendOrderAssembledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderAssembledEvent
func (_e *MockTelegramService_Expecter) SendOrderAssembledNotification(ctx interface{}, event interface{}) *MockTelegramService_SendOrderAssembledNotification_Call {
	return &MockTelegramService_SendOrderAssembledNotification_Call{Call: _e.mock.On("SendOrderAssembledNotification", ctx, event)}
}

func (_c *MockTelegramService_SendOrderAssembledNotification_Call) Run(run func(ctx context.Context, event model.OrderAssembledEvent)) *MockTelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.OrderAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTelegramService_SendOrderAssembledNotification_Call) Return(err error) *MockTelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTelegramService_SendOrderAssembledNotification_Call) RunAndReturn(run func(ctx context.Context, event model.OrderAssembledEvent) error) *MockTelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendOrderPaidNotification provides a mock function for the type MockTelegramService
func (_mock *MockTelegramService) SendOrderPaidNotification(ctx context.Context, event model.OrderPaidEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderPaidNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTelegramService_SendOrderPaidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderPaidNotification'
type MockTelegramService_SendOrderPaidNotification_Call struct {
	*mock.Call
}

// SendOrderPaidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidEvent
func (_e *MockTelegramService_Expecter) SendOrderPaidNotification(ctx interface{}, event interface{}) *MockTelegramService_SendOrderPaidNotification_Call {
	return &MockTelegramService_SendOrderPaidNotification_Call{Call: _e.mock.On("SendOrderPaidNotification", ctx, event)}
}

func (_c *MockTelegramService_SendOrderPaidNotification_Call) Run(run func(ctx context.Context, event model.OrderPaidEvent)) *MockTelegramService_SendOrderPaidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderPaidEvent
		if args[1] != nil {
			arg1 = args[1].(model.OrderPaidEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTelegramService_SendOrderPaidNotification_Call) Return(err error) *MockTelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTelegramService_SendOrderPaidNotification_Call) RunAndReturn(run func(ctx context.Context, event model.OrderPaidEvent) error) *MockTelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(run)
	return _c
}
