// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderAssembledConsumerService creates a new instance of MockOrderAssembledConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderAssembledConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderAssembledConsumerService {
	mock := &MockOrderAssembledConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderAssembledConsumerService is an autogenerated mock type for the OrderAssembledConsumerService type
type MockOrderAssembledConsumerService struct {
	mock.Mock
}

type MockOrderAssembledConsumerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderAssembledConsumerService) EXPECT() *MockOrderAssembledConsumerService_Expecter {
	return &MockOrderAssembledConsumerService_Expecter{mock: &_m.Mock}
}

// RunConsumer provides a mock function for the type MockOrderAssembledConsumerService
func (_mock *MockOrderAssembledConsumerService) RunConsumer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunConsumer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderAssembledConsumerService_RunConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsumer'
type MockOrderAssembledConsumerService_RunConsumer_Call struct {
	*mock.Call
}

// RunConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderAssembledConsumerService_Expecter) RunConsumer(ctx interface{}) *MockOrderAssembledConsumerService_RunConsumer_Call {
	return &MockOrderAssembledConsumerService_RunConsumer_Call{Call: _e.mock.On("RunConsumer", ctx)}
}

func (_c *MockOrderAssembledConsumerService_RunConsumer_Call) Run(run func(ctx context.Context)) *MockOrderAssembledConsumerService_RunConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderAssembledConsumerService_RunConsumer_Call) Return(err error) *MockOrderAssembledConsumerService_RunConsumer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderAssembledConsumerService_RunConsumer_Call) RunAndReturn(run func(ctx context.Context) error) *MockOrderAssembledConsumerService_RunConsumer_Call {
	_c.Call.Return(run)
	return _c
}
