// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: inventory/v1/inventory.proto

package inventory_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _inventory_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetPartRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetPartRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPartRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetPartRequestMultiError,
// or nil if none found.
func (m *GetPartRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPartRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = GetPartRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetPartRequestMultiError(errors)
	}

	return nil
}

func (m *GetPartRequest) _validateUuid(uuid string) error {
	if matched := _inventory_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetPartRequestMultiError is an error wrapping multiple validation errors
// returned by GetPartRequest.ValidateAll() if the designated constraints
// aren't met.
type GetPartRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPartRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPartRequestMultiError) AllErrors() []error { return m }

// GetPartRequestValidationError is the validation error returned by
// GetPartRequest.Validate if the designated constraints aren't met.
type GetPartRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPartRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPartRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPartRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPartRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPartRequestValidationError) ErrorName() string { return "GetPartRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetPartRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPartRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPartRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPartRequestValidationError{}

// Validate checks the field values on GetPartResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetPartResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPartResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPartResponseMultiError, or nil if none found.
func (m *GetPartResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPartResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPart() == nil {
		err := GetPartResponseValidationError{
			field:  "Part",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetPart()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetPartResponseValidationError{
					field:  "Part",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetPartResponseValidationError{
					field:  "Part",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPart()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPartResponseValidationError{
				field:  "Part",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetPartResponseMultiError(errors)
	}

	return nil
}

// GetPartResponseMultiError is an error wrapping multiple validation errors
// returned by GetPartResponse.ValidateAll() if the designated constraints
// aren't met.
type GetPartResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPartResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPartResponseMultiError) AllErrors() []error { return m }

// GetPartResponseValidationError is the validation error returned by
// GetPartResponse.Validate if the designated constraints aren't met.
type GetPartResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPartResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPartResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPartResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPartResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPartResponseValidationError) ErrorName() string { return "GetPartResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetPartResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPartResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPartResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPartResponseValidationError{}

// Validate checks the field values on ListPartsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListPartsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPartsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPartsRequestMultiError, or nil if none found.
func (m *ListPartsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPartsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPartsRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPartsRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPartsRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListPartsRequestMultiError(errors)
	}

	return nil
}

// ListPartsRequestMultiError is an error wrapping multiple validation errors
// returned by ListPartsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListPartsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPartsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPartsRequestMultiError) AllErrors() []error { return m }

// ListPartsRequestValidationError is the validation error returned by
// ListPartsRequest.Validate if the designated constraints aren't met.
type ListPartsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPartsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPartsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPartsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPartsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPartsRequestValidationError) ErrorName() string { return "ListPartsRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListPartsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPartsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPartsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPartsRequestValidationError{}

// Validate checks the field values on ListPartsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListPartsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPartsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPartsResponseMultiError, or nil if none found.
func (m *ListPartsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPartsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetParts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPartsResponseValidationError{
						field:  fmt.Sprintf("Parts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPartsResponseValidationError{
						field:  fmt.Sprintf("Parts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPartsResponseValidationError{
					field:  fmt.Sprintf("Parts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPartsResponseMultiError(errors)
	}

	return nil
}

// ListPartsResponseMultiError is an error wrapping multiple validation errors
// returned by ListPartsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListPartsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPartsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPartsResponseMultiError) AllErrors() []error { return m }

// ListPartsResponseValidationError is the validation error returned by
// ListPartsResponse.Validate if the designated constraints aren't met.
type ListPartsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPartsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPartsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPartsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPartsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPartsResponseValidationError) ErrorName() string {
	return "ListPartsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPartsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPartsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPartsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPartsResponseValidationError{}

// Validate checks the field values on Part with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Part) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Part with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PartMultiError, or nil if none found.
func (m *Part) ValidateAll() error {
	return m.validate(true)
}

func (m *Part) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = PartValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 255 {
		err := PartValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) > 2000 {
		err := PartValidationError{
			field:  "Description",
			reason: "value length must be at most 2000 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPrice() < 0 {
		err := PartValidationError{
			field:  "Price",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetStockQuantity() < 0 {
		err := PartValidationError{
			field:  "StockQuantity",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _Part_Category_NotInLookup[m.GetCategory()]; ok {
		err := PartValidationError{
			field:  "Category",
			reason: "value must not be in list [CATEGORY_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Category_name[int32(m.GetCategory())]; !ok {
		err := PartValidationError{
			field:  "Category",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetDimensions() == nil {
		err := PartValidationError{
			field:  "Dimensions",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetDimensions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PartValidationError{
					field:  "Dimensions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PartValidationError{
					field:  "Dimensions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDimensions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PartValidationError{
				field:  "Dimensions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetManufacturer() == nil {
		err := PartValidationError{
			field:  "Manufacturer",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetManufacturer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PartValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PartValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetManufacturer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PartValidationError{
				field:  "Manufacturer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	_Part_Tags_Unique := make(map[string]struct{}, len(m.GetTags()))

	for idx, item := range m.GetTags() {
		_, _ = idx, item

		if _, exists := _Part_Tags_Unique[item]; exists {
			err := PartValidationError{
				field:  fmt.Sprintf("Tags[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_Part_Tags_Unique[item] = struct{}{}
		}

		if l := utf8.RuneCountInString(item); l < 1 || l > 64 {
			err := PartValidationError{
				field:  fmt.Sprintf("Tags[%v]", idx),
				reason: "value length must be between 1 and 64 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	{
		sorted_keys := make([]string, len(m.GetMetadata()))
		i := 0
		for key := range m.GetMetadata() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetMetadata()[key]
			_ = val

			if val == nil {
				err := PartValidationError{
					field:  fmt.Sprintf("Metadata[%v]", key),
					reason: "value cannot be sparse, all pairs must be non-nil",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

			// no validation rules for Metadata[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, PartValidationError{
							field:  fmt.Sprintf("Metadata[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, PartValidationError{
							field:  fmt.Sprintf("Metadata[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return PartValidationError{
						field:  fmt.Sprintf("Metadata[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if m.GetCreatedAt() == nil {
		err := PartValidationError{
			field:  "CreatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUpdatedAt() == nil {
		err := PartValidationError{
			field:  "UpdatedAt",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PartMultiError(errors)
	}

	return nil
}

func (m *Part) _validateUuid(uuid string) error {
	if matched := _inventory_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartMultiError is an error wrapping multiple validation errors returned by
// Part.ValidateAll() if the designated constraints aren't met.
type PartMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartMultiError) AllErrors() []error { return m }

// PartValidationError is the validation error returned by Part.Validate if the
// designated constraints aren't met.
type PartValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartValidationError) ErrorName() string { return "PartValidationError" }

// Error satisfies the builtin error interface
func (e PartValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPart.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartValidationError{}

var _Part_Category_NotInLookup = map[Category]struct{}{
	0: {},
}

// Validate checks the field values on Dimensions with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Dimensions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Dimensions with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DimensionsMultiError, or
// nil if none found.
func (m *Dimensions) ValidateAll() error {
	return m.validate(true)
}

func (m *Dimensions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetLength() <= 0 {
		err := DimensionsValidationError{
			field:  "Length",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetWidth() <= 0 {
		err := DimensionsValidationError{
			field:  "Width",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetHeight() <= 0 {
		err := DimensionsValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetWeight() <= 0 {
		err := DimensionsValidationError{
			field:  "Weight",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DimensionsMultiError(errors)
	}

	return nil
}

// DimensionsMultiError is an error wrapping multiple validation errors
// returned by Dimensions.ValidateAll() if the designated constraints aren't met.
type DimensionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DimensionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DimensionsMultiError) AllErrors() []error { return m }

// DimensionsValidationError is the validation error returned by
// Dimensions.Validate if the designated constraints aren't met.
type DimensionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DimensionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DimensionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DimensionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DimensionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DimensionsValidationError) ErrorName() string { return "DimensionsValidationError" }

// Error satisfies the builtin error interface
func (e DimensionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDimensions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DimensionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DimensionsValidationError{}

// Validate checks the field values on Manufacturer with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Manufacturer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Manufacturer with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ManufacturerMultiError, or
// nil if none found.
func (m *Manufacturer) ValidateAll() error {
	return m.validate(true)
}

func (m *Manufacturer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 255 {
		err := ManufacturerValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetCountry()); l < 1 || l > 128 {
		err := ManufacturerValidationError{
			field:  "Country",
			reason: "value length must be between 1 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetWebsite() != "" {

		if uri, err := url.Parse(m.GetWebsite()); err != nil {
			err = ManufacturerValidationError{
				field:  "Website",
				reason: "value must be a valid URI",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else if !uri.IsAbs() {
			err := ManufacturerValidationError{
				field:  "Website",
				reason: "value must be absolute",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ManufacturerMultiError(errors)
	}

	return nil
}

// ManufacturerMultiError is an error wrapping multiple validation errors
// returned by Manufacturer.ValidateAll() if the designated constraints aren't met.
type ManufacturerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ManufacturerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ManufacturerMultiError) AllErrors() []error { return m }

// ManufacturerValidationError is the validation error returned by
// Manufacturer.Validate if the designated constraints aren't met.
type ManufacturerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ManufacturerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ManufacturerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ManufacturerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ManufacturerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ManufacturerValidationError) ErrorName() string { return "ManufacturerValidationError" }

// Error satisfies the builtin error interface
func (e ManufacturerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sManufacturer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ManufacturerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ManufacturerValidationError{}

// Validate checks the field values on Value with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Value) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Value with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ValueMultiError, or nil if none found.
func (m *Value) ValidateAll() error {
	return m.validate(true)
}

func (m *Value) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofKindPresent := false
	switch v := m.Kind.(type) {
	case *Value_StringValue:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofKindPresent = true
		// no validation rules for StringValue
	case *Value_Int64Value:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofKindPresent = true
		// no validation rules for Int64Value
	case *Value_DoubleValue:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofKindPresent = true
		// no validation rules for DoubleValue
	case *Value_BoolValue:
		if v == nil {
			err := ValueValidationError{
				field:  "Kind",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofKindPresent = true
		// no validation rules for BoolValue
	default:
		_ = v // ensures v is used
	}
	if !oneofKindPresent {
		err := ValueValidationError{
			field:  "Kind",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ValueMultiError(errors)
	}

	return nil
}

// ValueMultiError is an error wrapping multiple validation errors returned by
// Value.ValidateAll() if the designated constraints aren't met.
type ValueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValueMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValueMultiError) AllErrors() []error { return m }

// ValueValidationError is the validation error returned by Value.Validate if
// the designated constraints aren't met.
type ValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValueValidationError) ErrorName() string { return "ValueValidationError" }

// Error satisfies the builtin error interface
func (e ValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValueValidationError{}

// Validate checks the field values on PartsFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PartsFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartsFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PartsFilterMultiError, or
// nil if none found.
func (m *PartsFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *PartsFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	_PartsFilter_Uuids_Unique := make(map[string]struct{}, len(m.GetUuids()))

	for idx, item := range m.GetUuids() {
		_, _ = idx, item

		if _, exists := _PartsFilter_Uuids_Unique[item]; exists {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Uuids[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_PartsFilter_Uuids_Unique[item] = struct{}{}
		}

		if err := m._validateUuid(item); err != nil {
			err = PartsFilterValidationError{
				field:  fmt.Sprintf("Uuids[%v]", idx),
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	_PartsFilter_Names_Unique := make(map[string]struct{}, len(m.GetNames()))

	for idx, item := range m.GetNames() {
		_, _ = idx, item

		if _, exists := _PartsFilter_Names_Unique[item]; exists {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Names[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_PartsFilter_Names_Unique[item] = struct{}{}
		}

		if l := utf8.RuneCountInString(item); l < 1 || l > 255 {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Names[%v]", idx),
				reason: "value length must be between 1 and 255 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	_PartsFilter_Categories_Unique := make(map[Category]struct{}, len(m.GetCategories()))

	for idx, item := range m.GetCategories() {
		_, _ = idx, item

		if _, exists := _PartsFilter_Categories_Unique[item]; exists {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Categories[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_PartsFilter_Categories_Unique[item] = struct{}{}
		}

		if _, ok := _PartsFilter_Categories_NotInLookup[item]; ok {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Categories[%v]", idx),
				reason: "value must not be in list [0]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if _, ok := Category_name[int32(item)]; !ok {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Categories[%v]", idx),
				reason: "value must be one of the defined enum values",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	_PartsFilter_ManufacturerCountries_Unique := make(map[string]struct{}, len(m.GetManufacturerCountries()))

	for idx, item := range m.GetManufacturerCountries() {
		_, _ = idx, item

		if _, exists := _PartsFilter_ManufacturerCountries_Unique[item]; exists {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("ManufacturerCountries[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_PartsFilter_ManufacturerCountries_Unique[item] = struct{}{}
		}

		if l := utf8.RuneCountInString(item); l < 1 || l > 128 {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("ManufacturerCountries[%v]", idx),
				reason: "value length must be between 1 and 128 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	_PartsFilter_Tags_Unique := make(map[string]struct{}, len(m.GetTags()))

	for idx, item := range m.GetTags() {
		_, _ = idx, item

		if _, exists := _PartsFilter_Tags_Unique[item]; exists {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Tags[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_PartsFilter_Tags_Unique[item] = struct{}{}
		}

		if l := utf8.RuneCountInString(item); l < 1 || l > 64 {
			err := PartsFilterValidationError{
				field:  fmt.Sprintf("Tags[%v]", idx),
				reason: "value length must be between 1 and 64 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return PartsFilterMultiError(errors)
	}

	return nil
}

func (m *PartsFilter) _validateUuid(uuid string) error {
	if matched := _inventory_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PartsFilterMultiError is an error wrapping multiple validation errors
// returned by PartsFilter.ValidateAll() if the designated constraints aren't met.
type PartsFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartsFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartsFilterMultiError) AllErrors() []error { return m }

// PartsFilterValidationError is the validation error returned by
// PartsFilter.Validate if the designated constraints aren't met.
type PartsFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartsFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartsFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartsFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartsFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartsFilterValidationError) ErrorName() string { return "PartsFilterValidationError" }

// Error satisfies the builtin error interface
func (e PartsFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartsFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartsFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartsFilterValidationError{}

var _PartsFilter_Categories_NotInLookup = map[Category]struct{}{
	0: {},
}
