// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/voronovsg/rocket-factory/order/internal/model"
)

// NewMockIAMClient creates a new instance of MockIAMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAMClient {
	mock := &MockIAMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAMClient is an autogenerated mock type for the IAMClient type
type MockIAMClient struct {
	mock.Mock
}

type MockIAMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAMClient) EXPECT() *MockIAMClient_Expecter {
	return &MockIAMClient_Expecter{mock: &_m.Mock}
}

// Whoami provides a mock function for the type MockIAMClient
func (_mock *MockIAMClient) Whoami(ctx context.Context, sessionUUID string) (model.SessionData, error) {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 model.SessionData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.SessionData, error)); ok {
		return returnFunc(ctx, sessionUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.SessionData); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.SessionData)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAMClient_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type MockIAMClient_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID string
func (_e *MockIAMClient_Expecter) Whoami(ctx interface{}, sessionUUID interface{}) *MockIAMClient_Whoami_Call {
	return &MockIAMClient_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionUUID)}
}

func (_c *MockIAMClient_Whoami_Call) Run(run func(ctx context.Context, sessionUUID string)) *MockIAMClient_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAMClient_Whoami_Call) Return(sessionData model.SessionData, err error) *MockIAMClient_Whoami_Call {
	_c.Call.Return(sessionData, err)
	return _c
}

func (_c *MockIAMClient_Whoami_Call) RunAndReturn(run func(ctx context.Context, sessionUUID string) (model.SessionData, error)) *MockIAMClient_Whoami_Call {
	_c.Call.Return(run)
	return _c
}
