// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/user.proto

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Методы уведомления пользователя
type NotificationMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"` // Название провайдера
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`                                 // Цель уведомления: email, ID чата, токен устройства и т.д.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMethod) Reset() {
	*x = NotificationMethod{}
	mi := &file_common_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMethod) ProtoMessage() {}

func (x *NotificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMethod.ProtoReflect.Descriptor instead.
func (*NotificationMethod) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationMethod) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *NotificationMethod) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// Базовая информация о пользователе
type UserInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Login               string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`                                                        // Логин пользователя
	Email               string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                                        // Email пользователя
	NotificationMethods []*NotificationMethod  `protobuf:"bytes,3,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"` // Методы уведомления
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_common_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetNotificationMethods() []*NotificationMethod {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

// Полная информация о пользователе
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // Уникальный идентификатор пользователя
	Info          *UserInfo              `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`                            // Основная информация
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания пользователя
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Дата последнего обновления пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_common_v1_user_proto protoreflect.FileDescriptor

const file_common_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x14common/v1/user.proto\x12\tcommon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\x12NotificationMethod\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"\x88\x01\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12P\n" +
	"\x14notification_methods\x18\x03 \x03(\v2\x1d.common.v1.NotificationMethodR\x13notificationMethods\"\xb9\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12'\n" +
	"\x04info\x18\x02 \x01(\v2\x13.common.v1.UserInfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBJZHgithub.com/voronovsg/rocket-factory/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_user_proto_rawDescOnce sync.Once
	file_common_v1_user_proto_rawDescData []byte
)

func file_common_v1_user_proto_rawDescGZIP() []byte {
	file_common_v1_user_proto_rawDescOnce.Do(func() {
		file_common_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)))
	})
	return file_common_v1_user_proto_rawDescData
}

var file_common_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_v1_user_proto_goTypes = []any{
	(*NotificationMethod)(nil),    // 0: common.v1.NotificationMethod
	(*UserInfo)(nil),              // 1: common.v1.UserInfo
	(*User)(nil),                  // 2: common.v1.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_common_v1_user_proto_depIdxs = []int32{
	0, // 0: common.v1.UserInfo.notification_methods:type_name -> common.v1.NotificationMethod
	1, // 1: common.v1.User.info:type_name -> common.v1.UserInfo
	3, // 2: common.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: common.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_v1_user_proto_init() }
func file_common_v1_user_proto_init() {
	if File_common_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_user_proto_goTypes,
		DependencyIndexes: file_common_v1_user_proto_depIdxs,
		MessageInfos:      file_common_v1_user_proto_msgTypes,
	}.Build()
	File_common_v1_user_proto = out.File
	file_common_v1_user_proto_goTypes = nil
	file_common_v1_user_proto_depIdxs = nil
}
