// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumerService creates a new instance of MockConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerService {
	mock := &MockConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumerService is an autogenerated mock type for the ConsumerService type
type MockConsumerService struct {
	mock.Mock
}

type MockConsumerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumerService) EXPECT() *MockConsumerService_Expecter {
	return &MockConsumerService_Expecter{mock: &_m.Mock}
}

// RunConsumer provides a mock function for the type MockConsumerService
func (_mock *MockConsumerService) RunConsumer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunConsumer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumerService_RunConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsumer'
type MockConsumerService_RunConsumer_Call struct {
	*mock.Call
}

// RunConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConsumerService_Expecter) RunConsumer(ctx interface{}) *MockConsumerService_RunConsumer_Call {
	return &MockConsumerService_RunConsumer_Call{Call: _e.mock.On("RunConsumer", ctx)}
}

func (_c *MockConsumerService_RunConsumer_Call) Run(run func(ctx context.Context)) *MockConsumerService_RunConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumerService_RunConsumer_Call) Return(err error) *MockConsumerService_RunConsumer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumerService_RunConsumer_Call) RunAndReturn(run func(ctx context.Context) error) *MockConsumerService_RunConsumer_Call {
	_c.Call.Return(run)
	return _c
}
