// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/voronovsg/rocket-factory/assembly/internal/model"
)

// NewMockOrderProducerService creates a new instance of MockOrderProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderProducerService {
	mock := &MockOrderProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderProducerService is an autogenerated mock type for the OrderProducerService type
type MockOrderProducerService struct {
	mock.Mock
}

type MockOrderProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderProducerService) EXPECT() *MockOrderProducerService_Expecter {
	return &MockOrderProducerService_Expecter{mock: &_m.Mock}
}

// ProduceOrderAssembled provides a mock function for the type MockOrderProducerService
func (_mock *MockOrderProducerService) ProduceOrderAssembled(ctx context.Context, event model.OrderAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderAssembled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderProducerService_ProduceOrderAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderAssembled'
type MockOrderProducerService_ProduceOrderAssembled_Call struct {
	*mock.Call
}

// ProduceOrderAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderAssembledEvent
func (_e *MockOrderProducerService_Expecter) ProduceOrderAssembled(ctx interface{}, event interface{}) *MockOrderProducerService_ProduceOrderAssembled_Call {
	return &MockOrderProducerService_ProduceOrderAssembled_Call{Call: _e.mock.On("ProduceOrderAssembled", ctx, event)}
}

func (_c *MockOrderProducerService_ProduceOrderAssembled_Call) Run(run func(ctx context.Context, event model.OrderAssembledEvent)) *MockOrderProducerService_ProduceOrderAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.OrderAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderProducerService_ProduceOrderAssembled_Call) Return(err error) *MockOrderProducerService_ProduceOrderAssembled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderProducerService_ProduceOrderAssembled_Call) RunAndReturn(run func(ctx context.Context, event model.OrderAssembledEvent) error) *MockOrderProducerService_ProduceOrderAssembled_Call {
	_c.Call.Return(run)
	return _c
}
