// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: events/v1/order.proto

package events_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OrderPaid with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderPaid) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderPaid with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderPaidMultiError, or nil
// if none found.
func (m *OrderPaid) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderPaid) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderUuid

	// no validation rules for UserUuid

	// no validation rules for PaymentMethod

	// no validation rules for TransactionUuid

	if all {
		switch v := interface{}(m.GetPaidAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderPaidValidationError{
					field:  "PaidAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderPaidValidationError{
					field:  "PaidAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPaidAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderPaidValidationError{
				field:  "PaidAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return OrderPaidMultiError(errors)
	}

	return nil
}

// OrderPaidMultiError is an error wrapping multiple validation errors returned
// by OrderPaid.ValidateAll() if the designated constraints aren't met.
type OrderPaidMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderPaidMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderPaidMultiError) AllErrors() []error { return m }

// OrderPaidValidationError is the validation error returned by
// OrderPaid.Validate if the designated constraints aren't met.
type OrderPaidValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderPaidValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderPaidValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderPaidValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderPaidValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderPaidValidationError) ErrorName() string { return "OrderPaidValidationError" }

// Error satisfies the builtin error interface
func (e OrderPaidValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderPaid.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderPaidValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderPaidValidationError{}

// Validate checks the field values on OrderAssembled with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderAssembled) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderAssembled with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderAssembledMultiError,
// or nil if none found.
func (m *OrderAssembled) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderAssembled) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderUuid

	// no validation rules for UserUuid

	// no validation rules for BuildTimeSec

	if len(errors) > 0 {
		return OrderAssembledMultiError(errors)
	}

	return nil
}

// OrderAssembledMultiError is an error wrapping multiple validation errors
// returned by OrderAssembled.ValidateAll() if the designated constraints
// aren't met.
type OrderAssembledMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderAssembledMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderAssembledMultiError) AllErrors() []error { return m }

// OrderAssembledValidationError is the validation error returned by
// OrderAssembled.Validate if the designated constraints aren't met.
type OrderAssembledValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderAssembledValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderAssembledValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderAssembledValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderAssembledValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderAssembledValidationError) ErrorName() string { return "OrderAssembledValidationError" }

// Error satisfies the builtin error interface
func (e OrderAssembledValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderAssembled.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderAssembledValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderAssembledValidationError{}
