// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/voronovsg/rocket-factory/inventory/internal/model"
)

// NewMockPartService creates a new instance of MockPartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartService {
	mock := &MockPartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPartService is an autogenerated mock type for the PartService type
type MockPartService struct {
	mock.Mock
}

type MockPartService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartService) EXPECT() *MockPartService_Expecter {
	return &MockPartService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type MockPartService
func (_mock *MockPartService) GetPart(ctx context.Context, uuid string) (model.Part, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type MockPartService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockPartService_Expecter) GetPart(ctx interface{}, uuid interface{}) *MockPartService_GetPart_Call {
	return &MockPartService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuid)}
}

func (_c *MockPartService_GetPart_Call) Run(run func(ctx context.Context, uuid string)) *MockPartService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartService_GetPart_Call) Return(part model.Part, err error) *MockPartService_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockPartService_GetPart_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Part, error)) *MockPartService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type MockPartService
func (_mock *MockPartService) ListParts(ctx context.Context, filter model.PartsFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockPartService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartsFilter
func (_e *MockPartService_Expecter) ListParts(ctx interface{}, filter interface{}) *MockPartService_ListParts_Call {
	return &MockPartService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *MockPartService_ListParts_Call) Run(run func(ctx context.Context, filter model.PartsFilter)) *MockPartService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(model.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartService_ListParts_Call) Return(parts []model.Part, err error) *MockPartService_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockPartService_ListParts_Call) RunAndReturn(run func(ctx context.Context, filter model.PartsFilter) ([]model.Part, error)) *MockPartService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
