syntax = "proto3";

package common.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/voronovsg/rocket-factory/shared/pkg/proto/common/v1;common_v1";

// Информация о сессии пользователя
message Session {
  string uuid = 1; // Уникальный идентификатор сессии
  google.protobuf.Timestamp created_at = 2; // Дата и время создания сессии
  google.protobuf.Timestamp updated_at = 3; // Дата и время последнего обновления сессии
  google.protobuf.Timestamp expires_at = 4; // Дата и время истечения сессии
}
