// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderByUUIDRes interface {
	cancelOrderByUUIDRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderByUUIDRes interface {
	getOrderByUUIDRes()
}

type PayOrderRes interface {
	payOrderRes()
}
