// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"time"

	"github.com/google/uuid"
)

// SetFake set fake values.
func (s *BadGatewayError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *BadGatewayErrorCode) SetFake() {
	*s = BadGatewayErrorCode502
}

// SetFake set fake values.
func (s *BadRequestError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *BadRequestErrorCode) SetFake() {
	*s = BadRequestErrorCode400
}

// SetFake set fake values.
func (s *ConflictError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ConflictErrorCode) SetFake() {
	*s = ConflictErrorCode409
}

// SetFake set fake values.
func (s *CreateOrderRequest) SetFake() {
	{
		{
			s.UserUUID = uuid.New()
		}
	}
	{
		{
			s.PartUuids = nil
			for i := 0; i < 1; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.PartUuids = append(s.PartUuids, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateOrderResponse) SetFake() {
	{
		{
			s.Order.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ForbiddenError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ForbiddenErrorCode) SetFake() {
	*s = ForbiddenErrorCode403
}

// SetFake set fake values.
func (s *GenericError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GenericErrorCode) SetFake() {
	*s = GenericErrorCode520
}

// SetFake set fake values.
func (s *GetOrderResponse) SetFake() {
	{
		{
			s.Order.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InternalServerError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *InternalServerErrorCode) SetFake() {
	*s = InternalServerErrorCode500
}

// SetFake set fake values.
func (s *NotFoundError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *NotFoundErrorCode) SetFake() {
	*s = NotFoundErrorCode404
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilUUID) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptPaymentMethod) SetFake() {
	var elem PaymentMethod
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OrderDto) SetFake() {
	{
		{
			s.UUID = uuid.New()
		}
	}
	{
		{
			s.UserUUID = uuid.New()
		}
	}
	{
		{
			s.PartUuids = nil
			for i := 0; i < 0; i++ {
				var elem uuid.UUID
				{
					elem = uuid.New()
				}
				s.PartUuids = append(s.PartUuids, elem)
			}
		}
	}
	{
		{
			s.TotalPrice = float64(0)
		}
	}
	{
		{
			s.TransactionUUID.SetFake()
		}
	}
	{
		{
			s.PaymentMethod.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OrderStatus) SetFake() {
	*s = OrderStatusPENDINGPAYMENT
}

// SetFake set fake values.
func (s *PayOrderRequest) SetFake() {
	{
		{
			s.PaymentMethod.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PayOrderResponse) SetFake() {
	{
		{
			s.TransactionUUID = uuid.New()
		}
	}
}

// SetFake set fake values.
func (s *PaymentMethod) SetFake() {
	*s = PaymentMethodPAYMENTMETHODUNSPECIFIED
}

// SetFake set fake values.
func (s *RateLimitError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *RateLimitErrorCode) SetFake() {
	*s = RateLimitErrorCode429
}

// SetFake set fake values.
func (s *ServiceUnavailableError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ServiceUnavailableErrorCode) SetFake() {
	*s = ServiceUnavailableErrorCode503
}

// SetFake set fake values.
func (s *UnauthorizedError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *UnauthorizedErrorCode) SetFake() {
	*s = UnauthorizedErrorCode401
}

// SetFake set fake values.
func (s *ValidationError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *ValidationErrorCode) SetFake() {
	*s = ValidationErrorCode422
}
