// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #
type BadGatewayError struct {
	Code    BadGatewayErrorCode `json:"code"`
	Message string              `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadGatewayError) GetCode() BadGatewayErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadGatewayError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadGatewayError) SetCode(val BadGatewayErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadGatewayError) SetMessage(val string) {
	s.Message = val
}

func (*BadGatewayError) payOrderRes() {}

type BadGatewayErrorCode int

const (
	BadGatewayErrorCode502 BadGatewayErrorCode = 502
)

// AllValues returns all BadGatewayErrorCode values.
func (BadGatewayErrorCode) AllValues() []BadGatewayErrorCode {
	return []BadGatewayErrorCode{
		BadGatewayErrorCode502,
	}
}

// Ref: #
type BadRequestError struct {
	Code    BadRequestErrorCode `json:"code"`
	Message string              `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() BadRequestErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val BadRequestErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) createOrderRes() {}
func (*BadRequestError) payOrderRes()    {}

type BadRequestErrorCode int

const (
	BadRequestErrorCode400 BadRequestErrorCode = 400
)

// AllValues returns all BadRequestErrorCode values.
func (BadRequestErrorCode) AllValues() []BadRequestErrorCode {
	return []BadRequestErrorCode{
		BadRequestErrorCode400,
	}
}

// CancelOrderByUUIDNoContent is response for CancelOrderByUUID operation.
type CancelOrderByUUIDNoContent struct{}

func (*CancelOrderByUUIDNoContent) cancelOrderByUUIDRes() {}

// Ref: #
type ConflictError struct {
	Code    ConflictErrorCode `json:"code"`
	Message string            `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() ConflictErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val ConflictErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderByUUIDRes() {}
func (*ConflictError) payOrderRes()          {}

type ConflictErrorCode int

const (
	ConflictErrorCode409 ConflictErrorCode = 409
)

// AllValues returns all ConflictErrorCode values.
func (ConflictErrorCode) AllValues() []ConflictErrorCode {
	return []ConflictErrorCode{
		ConflictErrorCode409,
	}
}

// Ref: #
type CreateOrderRequest struct {
	// UUID пользователя, создающего заказ.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID компонентов для заказа.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #
type CreateOrderResponse struct {
	Order OrderDto `json:"order"`
}

// GetOrder returns the value of Order.
func (s *CreateOrderResponse) GetOrder() OrderDto {
	return s.Order
}

// SetOrder sets the value of Order.
func (s *CreateOrderResponse) SetOrder(val OrderDto) {
	s.Order = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #
type ForbiddenError struct {
	Code    ForbiddenErrorCode `json:"code"`
	Message string             `json:"message"`
}

// GetCode returns the value of Code.
func (s *ForbiddenError) GetCode() ForbiddenErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ForbiddenError) SetCode(val ForbiddenErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val string) {
	s.Message = val
}

func (*ForbiddenError) createOrderRes() {}
func (*ForbiddenError) payOrderRes()    {}

type ForbiddenErrorCode int

const (
	ForbiddenErrorCode403 ForbiddenErrorCode = 403
)

// AllValues returns all ForbiddenErrorCode values.
func (ForbiddenErrorCode) AllValues() []ForbiddenErrorCode {
	return []ForbiddenErrorCode{
		ForbiddenErrorCode403,
	}
}

// Ref: #
type GenericError struct {
	Code    GenericErrorCode `json:"code"`
	Message string           `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() GenericErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val GenericErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

type GenericErrorCode int

const (
	GenericErrorCode520 GenericErrorCode = 520
)

// AllValues returns all GenericErrorCode values.
func (GenericErrorCode) AllValues() []GenericErrorCode {
	return []GenericErrorCode{
		GenericErrorCode520,
	}
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #
type GetOrderResponse struct {
	Order OrderDto `json:"order"`
}

// GetOrder returns the value of Order.
func (s *GetOrderResponse) GetOrder() OrderDto {
	return s.Order
}

// SetOrder sets the value of Order.
func (s *GetOrderResponse) SetOrder(val OrderDto) {
	s.Order = val
}

func (*GetOrderResponse) getOrderByUUIDRes() {}

// Ref: #
type InternalServerError struct {
	Code    InternalServerErrorCode `json:"code"`
	Message string                  `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() InternalServerErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val InternalServerErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) createOrderRes() {}
func (*InternalServerError) payOrderRes()    {}

type InternalServerErrorCode int

const (
	InternalServerErrorCode500 InternalServerErrorCode = 500
)

// AllValues returns all InternalServerErrorCode values.
func (InternalServerErrorCode) AllValues() []InternalServerErrorCode {
	return []InternalServerErrorCode{
		InternalServerErrorCode500,
	}
}

// Ref: #
type NotFoundError struct {
	Code    NotFoundErrorCode `json:"code"`
	Message string            `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() NotFoundErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val NotFoundErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderByUUIDRes() {}
func (*NotFoundError) getOrderByUUIDRes()    {}
func (*NotFoundError) payOrderRes()          {}

type NotFoundErrorCode int

const (
	NotFoundErrorCode404 NotFoundErrorCode = 404
)

// AllValues returns all NotFoundErrorCode values.
func (NotFoundErrorCode) AllValues() []NotFoundErrorCode {
	return []NotFoundErrorCode{
		NotFoundErrorCode404,
	}
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethod returns new OptPaymentMethod with value set to v.
func NewOptPaymentMethod(v PaymentMethod) OptPaymentMethod {
	return OptPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethod is optional PaymentMethod.
type OptPaymentMethod struct {
	Value PaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethod was set.
func (o OptPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #
type OrderDto struct {
	// UUID заказа.
	UUID uuid.UUID `json:"uuid"`
	// UUID пользователя, сделавшего заказ.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей, включённых в заказ.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Общая стоимость заказа.
	TotalPrice float64 `json:"total_price"`
	// UUID транзакции оплаты.
	TransactionUUID OptNilUUID       `json:"transaction_uuid"`
	PaymentMethod   OptPaymentMethod `json:"payment_method"`
	Status          OrderStatus      `json:"status"`
	// Дата и время создания заказа.
	CreatedAt time.Time `json:"created_at"`
	// Дата и время последнего обновления заказа.
	UpdatedAt OptDateTime `json:"updated_at"`
}

// GetUUID returns the value of UUID.
func (s *OrderDto) GetUUID() uuid.UUID {
	return s.UUID
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderDto) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderDto) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderDto) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderDto) GetTransactionUUID() OptNilUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderDto) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderDto) GetStatus() OrderStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OrderDto) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *OrderDto) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetUUID sets the value of UUID.
func (s *OrderDto) SetUUID(val uuid.UUID) {
	s.UUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderDto) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderDto) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderDto) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderDto) SetTransactionUUID(val OptNilUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderDto) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderDto) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OrderDto) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *OrderDto) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// Текущий статус заказа.
// Ref: #
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #
type PayOrderResponse struct {
	// UUID транзакции оплаты.
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Способ оплаты.
// Ref: #
type PaymentMethod string

const (
	PaymentMethodPAYMENTMETHODUNSPECIFIED   PaymentMethod = "PAYMENT_METHOD_UNSPECIFIED"
	PaymentMethodPAYMENTMETHODCARD          PaymentMethod = "PAYMENT_METHOD_CARD"
	PaymentMethodPAYMENTMETHODSBP           PaymentMethod = "PAYMENT_METHOD_SBP"
	PaymentMethodPAYMENTMETHODCREDITCARD    PaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	PaymentMethodPAYMENTMETHODINVESTORMONEY PaymentMethod = "PAYMENT_METHOD_INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodPAYMENTMETHODUNSPECIFIED,
		PaymentMethodPAYMENTMETHODCARD,
		PaymentMethodPAYMENTMETHODSBP,
		PaymentMethodPAYMENTMETHODCREDITCARD,
		PaymentMethodPAYMENTMETHODINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodPAYMENTMETHODUNSPECIFIED:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODSBP:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodPAYMENTMETHODUNSPECIFIED:
		*s = PaymentMethodPAYMENTMETHODUNSPECIFIED
		return nil
	case PaymentMethodPAYMENTMETHODCARD:
		*s = PaymentMethodPAYMENTMETHODCARD
		return nil
	case PaymentMethodPAYMENTMETHODSBP:
		*s = PaymentMethodPAYMENTMETHODSBP
		return nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		*s = PaymentMethodPAYMENTMETHODCREDITCARD
		return nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		*s = PaymentMethodPAYMENTMETHODINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #
type RateLimitError struct {
	Code    RateLimitErrorCode `json:"code"`
	Message string             `json:"message"`
}

// GetCode returns the value of Code.
func (s *RateLimitError) GetCode() RateLimitErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *RateLimitError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *RateLimitError) SetCode(val RateLimitErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *RateLimitError) SetMessage(val string) {
	s.Message = val
}

func (*RateLimitError) createOrderRes() {}
func (*RateLimitError) payOrderRes()    {}

type RateLimitErrorCode int

const (
	RateLimitErrorCode429 RateLimitErrorCode = 429
)

// AllValues returns all RateLimitErrorCode values.
func (RateLimitErrorCode) AllValues() []RateLimitErrorCode {
	return []RateLimitErrorCode{
		RateLimitErrorCode429,
	}
}

// Ref: #
type ServiceUnavailableError struct {
	Code    ServiceUnavailableErrorCode `json:"code"`
	Message string                      `json:"message"`
}

// GetCode returns the value of Code.
func (s *ServiceUnavailableError) GetCode() ServiceUnavailableErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ServiceUnavailableError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ServiceUnavailableError) SetCode(val ServiceUnavailableErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ServiceUnavailableError) SetMessage(val string) {
	s.Message = val
}

func (*ServiceUnavailableError) createOrderRes() {}
func (*ServiceUnavailableError) payOrderRes()    {}

type ServiceUnavailableErrorCode int

const (
	ServiceUnavailableErrorCode503 ServiceUnavailableErrorCode = 503
)

// AllValues returns all ServiceUnavailableErrorCode values.
func (ServiceUnavailableErrorCode) AllValues() []ServiceUnavailableErrorCode {
	return []ServiceUnavailableErrorCode{
		ServiceUnavailableErrorCode503,
	}
}

// Ref: #
type UnauthorizedError struct {
	Code    UnauthorizedErrorCode `json:"code"`
	Message string                `json:"message"`
}

// GetCode returns the value of Code.
func (s *UnauthorizedError) GetCode() UnauthorizedErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *UnauthorizedError) SetCode(val UnauthorizedErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val string) {
	s.Message = val
}

func (*UnauthorizedError) createOrderRes() {}
func (*UnauthorizedError) payOrderRes()    {}

type UnauthorizedErrorCode int

const (
	UnauthorizedErrorCode401 UnauthorizedErrorCode = 401
)

// AllValues returns all UnauthorizedErrorCode values.
func (UnauthorizedErrorCode) AllValues() []UnauthorizedErrorCode {
	return []UnauthorizedErrorCode{
		UnauthorizedErrorCode401,
	}
}

// Ref: #
type ValidationError struct {
	Code    ValidationErrorCode `json:"code"`
	Message string              `json:"message"`
}

// GetCode returns the value of Code.
func (s *ValidationError) GetCode() ValidationErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ValidationError) SetCode(val ValidationErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val string) {
	s.Message = val
}

func (*ValidationError) createOrderRes() {}
func (*ValidationError) payOrderRes()    {}

type ValidationErrorCode int

const (
	ValidationErrorCode422 ValidationErrorCode = 422
)

// AllValues returns all ValidationErrorCode values.
func (ValidationErrorCode) AllValues() []ValidationErrorCode {
	return []ValidationErrorCode{
		ValidationErrorCode422,
	}
}
