// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"github.com/go-faster/jx"

	std "encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestBadGatewayError_EncodeDecode(t *testing.T) {
	var typ BadGatewayError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 BadGatewayError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestBadGatewayErrorCode_EncodeDecode(t *testing.T) {
	var typ BadGatewayErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 BadGatewayErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestBadRequestError_EncodeDecode(t *testing.T) {
	var typ BadRequestError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 BadRequestError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestBadRequestErrorCode_EncodeDecode(t *testing.T) {
	var typ BadRequestErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 BadRequestErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestConflictError_EncodeDecode(t *testing.T) {
	var typ ConflictError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ConflictError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestConflictErrorCode_EncodeDecode(t *testing.T) {
	var typ ConflictErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ConflictErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCreateOrderRequest_EncodeDecode(t *testing.T) {
	var typ CreateOrderRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CreateOrderRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCreateOrderResponse_EncodeDecode(t *testing.T) {
	var typ CreateOrderResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CreateOrderResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestForbiddenError_EncodeDecode(t *testing.T) {
	var typ ForbiddenError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ForbiddenError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestForbiddenErrorCode_EncodeDecode(t *testing.T) {
	var typ ForbiddenErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ForbiddenErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGenericError_EncodeDecode(t *testing.T) {
	var typ GenericError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GenericError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGenericErrorCode_EncodeDecode(t *testing.T) {
	var typ GenericErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GenericErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGetOrderResponse_EncodeDecode(t *testing.T) {
	var typ GetOrderResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetOrderResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestInternalServerError_EncodeDecode(t *testing.T) {
	var typ InternalServerError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 InternalServerError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestInternalServerErrorCode_EncodeDecode(t *testing.T) {
	var typ InternalServerErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 InternalServerErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestNotFoundError_EncodeDecode(t *testing.T) {
	var typ NotFoundError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 NotFoundError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestNotFoundErrorCode_EncodeDecode(t *testing.T) {
	var typ NotFoundErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 NotFoundErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestOrderDto_EncodeDecode(t *testing.T) {
	var typ OrderDto
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 OrderDto
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestOrderStatus_EncodeDecode(t *testing.T) {
	var typ OrderStatus
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 OrderStatus
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPayOrderRequest_EncodeDecode(t *testing.T) {
	var typ PayOrderRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PayOrderRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPayOrderResponse_EncodeDecode(t *testing.T) {
	var typ PayOrderResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PayOrderResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPaymentMethod_EncodeDecode(t *testing.T) {
	var typ PaymentMethod
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PaymentMethod
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestRateLimitError_EncodeDecode(t *testing.T) {
	var typ RateLimitError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 RateLimitError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestRateLimitErrorCode_EncodeDecode(t *testing.T) {
	var typ RateLimitErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 RateLimitErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestServiceUnavailableError_EncodeDecode(t *testing.T) {
	var typ ServiceUnavailableError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ServiceUnavailableError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestServiceUnavailableErrorCode_EncodeDecode(t *testing.T) {
	var typ ServiceUnavailableErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ServiceUnavailableErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestUnauthorizedError_EncodeDecode(t *testing.T) {
	var typ UnauthorizedError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 UnauthorizedError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestUnauthorizedErrorCode_EncodeDecode(t *testing.T) {
	var typ UnauthorizedErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 UnauthorizedErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestValidationError_EncodeDecode(t *testing.T) {
	var typ ValidationError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ValidationError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestValidationErrorCode_EncodeDecode(t *testing.T) {
	var typ ValidationErrorCode
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ValidationErrorCode
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
