// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/voronovsg/rocket-factory/order/internal/model"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CancelOrderByUUID provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CancelOrderByUUID(ctx context.Context, orderUUID string) error {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderByUUID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_CancelOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderByUUID'
type MockOrderService_CancelOrderByUUID_Call struct {
	*mock.Call
}

// CancelOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *MockOrderService_Expecter) CancelOrderByUUID(ctx interface{}, orderUUID interface{}) *MockOrderService_CancelOrderByUUID_Call {
	return &MockOrderService_CancelOrderByUUID_Call{Call: _e.mock.On("CancelOrderByUUID", ctx, orderUUID)}
}

func (_c *MockOrderService_CancelOrderByUUID_Call) Run(run func(ctx context.Context, orderUUID string)) *MockOrderService_CancelOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_CancelOrderByUUID_Call) Return(err error) *MockOrderService_CancelOrderByUUID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_CancelOrderByUUID_Call) RunAndReturn(run func(ctx context.Context, orderUUID string) error) *MockOrderService_CancelOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CreateOrder(ctx context.Context, createOrder model.CreateOrder) (model.Order, error) {
	ret := _mock.Called(ctx, createOrder)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrder) (model.Order, error)); ok {
		return returnFunc(ctx, createOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateOrder) model.Order); ok {
		r0 = returnFunc(ctx, createOrder)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreateOrder) error); ok {
		r1 = returnFunc(ctx, createOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - createOrder model.CreateOrder
func (_e *MockOrderService_Expecter) CreateOrder(ctx interface{}, createOrder interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, createOrder)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, createOrder model.CreateOrder)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateOrder
		if args[1] != nil {
			arg1 = args[1].(model.CreateOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(order model.Order, err error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, createOrder model.CreateOrder) (model.Order, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUUID provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrderByUUID(ctx context.Context, orderUUID string) (model.Order, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_GetOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUUID'
type MockOrderService_GetOrderByUUID_Call struct {
	*mock.Call
}

// GetOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *MockOrderService_Expecter) GetOrderByUUID(ctx interface{}, orderUUID interface{}) *MockOrderService_GetOrderByUUID_Call {
	return &MockOrderService_GetOrderByUUID_Call{Call: _e.mock.On("GetOrderByUUID", ctx, orderUUID)}
}

func (_c *MockOrderService_GetOrderByUUID_Call) Run(run func(ctx context.Context, orderUUID string)) *MockOrderService_GetOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrderByUUID_Call) Return(order model.Order, err error) *MockOrderService_GetOrderByUUID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderService_GetOrderByUUID_Call) RunAndReturn(run func(ctx context.Context, orderUUID string) (model.Order, error)) *MockOrderService_GetOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) PayOrder(ctx context.Context, orderUUID string, payMethod string) (string, error) {
	ret := _mock.Called(ctx, orderUUID, payMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, orderUUID, payMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, orderUUID, payMethod)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orderUUID, payMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockOrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - payMethod string
func (_e *MockOrderService_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, payMethod interface{}) *MockOrderService_PayOrder_Call {
	return &MockOrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, payMethod)}
}

func (_c *MockOrderService_PayOrder_Call) Run(run func(ctx context.Context, orderUUID string, payMethod string)) *MockOrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_PayOrder_Call) Return(s string, err error) *MockOrderService_PayOrder_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOrderService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID string, payMethod string) (string, error)) *MockOrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
