services:
  mongo-inventory:
    image: ${MONGO_IMAGE_NAME}
    container_name: mongo-inventory
    env_file:
      - .env
    volumes:
      - mongo_inventory_data:/data/db
    ports:
      - "${MONGO_EXTERNAL_PORT}:27017" # порт хоста: порт контейнера
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase ${MONGO_AUTH_DB} | grep -q 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - microservices-net
volumes:
  mongo_inventory_data:
networks:
  microservices-net:
    external: true # Подключаемся к существующей сети

