syntax = "proto3";

package inventory.v1;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "github.com/voronovsg/rocket-factory/inventory/proto/inventory/v1;inventory_v1";

// Сервис InventoryService
service InventoryService {
  // GetPart Возвращает информацию о детали по её UUID
  rpc GetPart(GetPartRequest) returns (GetPartResponse) {
    option (google.api.http) = {
      get: "/api/v1/GetPart/{uuid}"
    };
  };

  // ListParts Получает список деталей с возможностью фильтрации
  rpc ListParts(ListPartsRequest) returns (ListPartsResponse) {
    option (google.api.http) = {
      post: "/api/v1/ListParts"
      body: "*"
    };
  };
}

// Запрос для метода GetPart
message GetPartRequest {
  string uuid = 1; // Идентификатор запрашиваемой детали
}

// Ответ для метода GetPart
message GetPartResponse {
  Part part = 1; // Информация о найденной детали
}

// Запрос для метода ListParts
message ListPartsRequest {
  PartsFilter filter = 1; // Фильтр для поиска деталей
}

// Ответ для метода ListParts
message ListPartsResponse {
  repeated Part parts = 1; // Список найденных деталей
}

// Структура, описывающая деталь
message Part {
  string uuid = 1; // Уникальный идентификатор детали
  string name = 2; // Название детали
  string description = 3; // Описание детали
  double price = 4; // Цена за единицу
  int64 stock_quantity = 5; // Количество на складе
  Category category = 6; // Категория
  Dimensions dimensions = 7; // Размеры детали
  Manufacturer manufacturer = 8; // Информация о производителе
  repeated string tags = 9; // Теги для быстрого поиска
  map<string, Value> metadata = 10; // Гибкие метаданные
  google.protobuf.Timestamp created_at = 11; // Дата создания
  google.protobuf.Timestamp updated_at = 12; // Дата обновления
}

// Категории деталей
enum Category {
  CATEGORY_UNSPECIFIED = 0; // Неизвестная категория
  CATEGORY_ENGINE = 1; // Двигатель
  CATEGORY_FUEL = 2; // Топливо
  CATEGORY_PORTHOLE = 3; // Иллюминатор
  CATEGORY_WING = 4; // Крыло
}

// Dimensions представляет размеры детали
message Dimensions {
  double length = 1; // Длина в см
  double width = 2; // Ширина в см
  double height = 3; // Высота в см
  double weight = 4; // Вес в кг
}

// Структура для хранения информации о производителе детали
message Manufacturer {
  string name = 1; // Название производителя
  string country = 2; // Страна производства
  string website = 3; // Сайт производителя
}

// Структура для хранения значения метаданных детали
message Value {
  oneof kind {
    string string_value = 1; // Строковое значение
    int64 int64_value = 2; // Целочисленное значение
    double double_value = 3; // Дробное значение
    bool bool_value = 4; // Логическое значение
  }
}

// Фильтр для поиска деталей
message PartsFilter {
  repeated string uuids = 1; // Список UUID'ов деталей
  repeated string names = 2; // Список имён деталей
  repeated Category categories = 3; // Список категорий деталей
  repeated string manufacturer_countries = 4; // Страны производителей
  repeated string tags = 5; // Теги для поиска
}